#!/bin/bash
cat > "$C_HOME/environment" <<'EOF'
if [ -d "$HOME/.local/bin" ] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi
export LESS='-RXF --use-color -Dd+r$Du+b'
EOF
